# Aljabar Matriks

## Pengertian Dari Matriks
Matriks adalah sekumpulan bilangan yang merepresentasikan tujuan tertentu dan terorganisasi dalam baris dan kolom. Dalam aljabar matriks, matriks adalah susunan bilangan yang tersusun dalam baris dan kolom dan ditulis dalam kurung siku. Elemen-elemen matriks disebut juga entri atau elemen matriks. Matriks memiliki ukuran matriks yang disebut ordo, yaitu banyak baris × banyak kolom. Adanya berbagai jenis matriks, seperti matriks bujur sangkar, matriks segitiga atas, matriks segitiga bawah, matriks diagonal, matriks satuan, matriks nol, dan matriks invers. Matriks dapat digunakan untuk mengoperasikan dan menyelesaikan sistem persamaan linear. [matriks](https://mamikos.com/info/pengertian-matriks-pljr/)

Aljabar matriks adalah cabang matematika yang mempelajari tentang matriks dan operasi-operasi yang dapat dilakukan pada matriks. Aljabar matriks mempelajari cara mengolah dan memanipulasi matriks untuk mencari solusi dari masalah-masalah matematika yang kompleks. Dalam aljabar matriks, kita dapat melakukan berbagai operasi matematika seperti penjumlahan, pengurangan, perkalian, dan pembagian matriks. Kita juga dapat melakukan operasi seperti transpose, invers, dan determinan pada matriks. Operasi-operasi ini sangat penting dalam pemecahan masalah-masalah linier, yaitu masalah yang dapat dinyatakan sebagai sistem persamaan linier. Aljabar matriks juga memiliki banyak aplikasi dalam bidang-bidang seperti teori graf, teori kendali, dan sistem linier.[AljabarMatriks1](https://myedu.ums.ac.id/courses/aljabar-matriks/?cl=1), [AljabarMatriks2](https://scholar.ui.ac.id/en/publications/aljabar-matriks)

## Contoh bentuk dari matriks

$$
\begin{bmatrix}
0 & 4 & 4 \\
8 & 2 & 4 \\
4 & 9 & 3
\end{bmatrix}
$$

## Penggunaan Numpy pada Aljabar Matriks

Numpy adalah pustaka Python yang dirancang khusus untuk manipulasi data numerik. Pustaka ini memberikan struktur data array yang efisien serta beragam fungsi matematika untuk operasi numerik. Numpy tidak hanya memberikan alternatif terhadap list Python yang umum digunakan, melainkan juga menyediakan operasi-operasi yang dioptimalkan secara efisien untuk data bertipe numerik. Dengan kata lain, Numpy menjadi solusi ideal untuk pengolahan data skalar, vektor, matriks, atau bahkan data yang lebih kompleks. Memungkinkan pengguna untuk melakukan operasi matematika, perpindahan, dan perhitungan terhadap matriks dan array dengan cepat dan efisien. Selain itu, Numpy memiliki fitur-fitur lain, seperti membuat matriks dan array, mengakses elemen matriks dan array, mengubah ukuran matriks dan array, serta membuat dan memanipulasi grafik. Karena fleksibilitas dan kinerja tinggi, Numpy banyak digunakan dalam berbagai bidang, seperti statistika, fisika, dan teori matematika.[Numpy](https://blog.indobot.co.id/penjelasan-mengenai-apa-itu-numpy-dan-fungsinya-pada-data-science/)

## Operasi-operasi pada matriks dengan menggunakan numpy
### 1. Penjumlahan Matriks
Penjumlahan matriks adalah operasi matematika yang melibatkan dua matriks dengan dimensi yang sama, dan elemen-elemen mereka dijumlahkan secara berpasangan untuk membentuk matriks baru. Operasi penjumlahan matriks sering digunakan dalam berbagai aplikasi, seperti pengolahan citra, analisis data, dan pemodelan matematika

$$
\begin{bmatrix}
2 & 4 \\
8 & 2 
\end{bmatrix}
+
\begin{bmatrix}
5 & 6 \\
7 & 8 
\end{bmatrix}
$$


In [16]:
import numpy as np

# Membuat matriks
A = np.array([[2, 4], [8, 2]])
B = np.array([[5, 6], [7, 8]])

# Penjumlahan matriks
C = np.add(A, B)
print(C)

[[ 7 10]
 [15 10]]


### 2. Pengurangan Matriks
Pengurangan matriks merupakan operasi untuk mengurangi elemen-elemen matriks yang sama. Jika matriks A dan B memiliki ukuran yang sama, maka matriks A - B dapat diperoleh dengan menurunkan elemen-elemen yang sama di setiap baris dan kolom

$$
\begin{bmatrix}
2 & 4 \\
8 & 2 
\end{bmatrix}
-
\begin{bmatrix}
5 & 6 \\
7 & 8 
\end{bmatrix}
$$


In [17]:
import numpy as np

# Membuat matriks
A = np.array([[2, 4], [8, 2]])
B = np.array([[5, 6], [7, 8]])

# Pengurangan matriks
C = np.subtract(A, B)
print(C)

[[-3 -2]
 [ 1 -6]]


### 3. Perkalian Matriks
Perkalian matriks merupakan operasi untuk mengalikan elemen-elemen matriks yang berada pada baris dan kolom yang sama. Jika matriks A dan B memiliki ukuran yang sama, maka matriks A * B dapat diperoleh dengan mengalikan elemen-elemen yang berada pada baris dan kolom yang sama, lalu menjumlahkan hasil perkalian tersebut pada kolom yang sama

$$
\begin{bmatrix}
2 & 4 \\
8 & 2 
\end{bmatrix}
*
\begin{bmatrix}
5 & 6 \\
7 & 8 
\end{bmatrix}
$$


In [18]:
# Menggunakan method dari library numpy
import numpy as np

# Membuat matriks
A = np.array([[2, 4], [8, 2]])
B = np.array([[5, 6], [7, 8]])

# Perkalian matriks
C = np.dot(A, B)
print(C)

[[38 44]
 [54 64]]


In [2]:
# Menggunakan @ 
import numpy as np

# Membuat matriks
A = np.array([[2, 4], [8, 2]])
B = np.array([[5, 6], [7, 8]])

# Perkalian Matriks
C = A @ B 
print(C)


[[38 44]
 [54 64]]


### 4. Transpose Matriks
Transpose matriks merupakan operasi untuk mengubah matriks menjadi matriks transpose. Jika matriks A memiliki ukuran m x n, maka matriks A' memiliki ukuran n x m, dengan baris-barisnya adalah kolom-kolom dari matriks A

$$
\begin{bmatrix}
2 & 4 \\
8 & 2 \\
6 & 9
\end{bmatrix}

$$


In [19]:
import numpy as np

# Membuat matriks
A = np.array([[2, 4], [8, 2],[6, 9]])

# transpose matriks
C = np.transpose(A)
print(C)

[[2 8 6]
 [4 2 9]]


### 5. Determinan Matriks
Determinan matriks merupakan nilai yang diperoleh dari perkalian elemen-elemen matriks yang berada pada diagonal utama. Jika matriks A memiliki ukuran n x n, maka determinan matriks A dapat diperoleh dengan menjumlahkan elemen-elemen yang berada pada diagonal utam

$$
\begin{bmatrix}
2 & 4 \\
8 & 2 
\end{bmatrix}

$$


In [20]:
import numpy as np

# Membuat matriks
A = np.array([[2, 4], [8, 2]])

# transpose matriks
C = np.linalg.det(A)
print(C)

-27.999999999999996


### 6. Invers Matriks
Invers matriks merupakan matriks yang dapat mengbalikkan operasi perkalian matriks. Jika matriks A memiliki ukuran n x n, maka matriks A⁻¹ 
dapat diperoleh dengan menghitung invers matriks A

$$
\begin{bmatrix}
2 & 4 \\
8 & 2 
\end{bmatrix}
$$


In [21]:
import numpy as np

# Membuat matriks
A = np.array([[2, 4], [8, 2]])

# transpose matriks
C = np.linalg.inv(A)
print(C)

[[-0.07142857  0.14285714]
 [ 0.28571429 -0.07142857]]


In [11]:
import numpy as np

# Membuat matriks
A = np.array([[2,5,4], [8,2,4],[3,6,9]])
B = np.array([[5,7], [7, 8],[6,9]])

# Perkalian Matriks
C = np.dot(A,B)
# C = A @ B 
print(C)

[[ 69  90]
 [ 78 108]
 [111 150]]
