<!-- Tugas Komputasi aljabar linier -->

<!-- Judul dari Materi tugas dan Hari ini -->
# Matrix Invers 
 cerita matrix invers : teori tentang matrix invers........

## sifat sifat matrix invers
cerita......

## mencari invers matriks invers dengan eliminasi gaus jordan
contoh soal........

## penyelesaian sistem persamaan linien menggunakan matrix invers
contoh penyelesaian.........
<!-- note tidak boleh menggunakan fungsi invers pada numpy -->

### membuat soal 4 persamaan 4 variabel cari solusinya pakai invers matriks
contoh soal..........
contoh penyelesaian.........
<!-- note tidak boleh menggunakan fungsi invers pada numpy -->



# *Judul Pada Tulisan*

## Matriks Invers



In [1]:
import numpy as np 

A = np.array([[2, 1], [1, 1]])
B = np.array([[1, 0], [0, 1]])

# Perkalian matriks
C = np.dot(A, B)
print(C)

[[2 1]
 [1 1]]


In [2]:
import numpy as np 

A = np.array([[1, 0], [0, 1]])
B = np.array([[2, 1], [1, 1]])

# Perkalian matriks
C = np.dot(A, B)
print(C)

[[2 1]
 [1 1]]


carilah invers dari matrix dengan eliminasi gauss

$$
\begin{bmatrix}
a & b \\
c & d 
\end{bmatrix}
$$




In [10]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [9]:
A=np.array([[2,2,1, 1,0,0],[4,2,3, 0,1,0],[1,3,-1, 0,0,1]])
print(A)


[[ 2  2  1  1  0  0]
 [ 4  2  3  0  1  0]
 [ 1  3 -1  0  0  1]]


In [50]:
a1 = RowAdd(A,0,1,-2)
print(a1, '\n')

a2 = RowAdd(a1,0,2,-1)
print(a2, '\n')

a3 = RowScale(a2,0,1/2)
print(a3, '\n')

a4 = RowAdd(a3,0,2,1)
print(a4, '\n')

a5 = RowAdd(a4,1,2,1)
print(a5, '\n')

a6 = RowScale(a5,1,1/2)
print(a6, '\n')

a7 = RowAdd(a6,1,0,1)
print(a7, '\n')

a8 = RowScale(a7,1,1/0.5)
print(a8, '\n')

a9 = RowScale(a8,1,-2)
print(a9, '\n')


[[ 2.  2.  1.  1.  0.  0.]
 [ 0. -2.  1. -2.  1.  0.]
 [ 1.  3. -1.  0.  0.  1.]] 

[[ 2.  2.  1.  1.  0.  0.]
 [ 0. -2.  1. -2.  1.  0.]
 [-1.  1. -2. -1.  0.  1.]] 

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.  -2.   1.  -2.   1.   0. ]
 [-1.   1.  -2.  -1.   0.   1. ]] 

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.  -2.   1.  -2.   1.   0. ]
 [ 0.   2.  -1.5 -0.5  0.   1. ]] 

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.  -2.   1.  -2.   1.   0. ]
 [ 0.   0.  -0.5 -2.5  1.   1. ]] 

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.  -1.   0.5 -1.   0.5  0. ]
 [ 0.   0.  -0.5 -2.5  1.   1. ]] 

[[ 1.   0.   1.  -0.5  0.5  0. ]
 [ 0.  -1.   0.5 -1.   0.5  0. ]
 [ 0.   0.  -0.5 -2.5  1.   1. ]] 

[[ 1.   0.   1.  -0.5  0.5  0. ]
 [ 0.  -2.   1.  -2.   1.   0. ]
 [ 0.   0.  -0.5 -2.5  1.   1. ]] 

[[ 1.   0.   1.  -0.5  0.5  0. ]
 [-0.   4.  -2.   4.  -2.  -0. ]
 [ 0.   0.  -0.5 -2.5  1.   1. ]] 

