# Materi Determinan Matriks

## Pengertian dari Determinan Matriks 

Determinan adalah nilai yang dapat dihitung dari unsur-unsur suatu matriks persegi. Matriks persegi adalah matriks yang memiliki jumlah baris dan kolom yang sama, sehingga kalau kita gambarkan bentuk matriksnya, akan membentuk bangun layaknya persegi. Rumus dari determinan Matriks adalah sebagai berikut ini 

### Operasi determinan matriks 2X2

$$ A = \begin{bmatrix}
a & b  \\
c & d  \\
\end{bmatrix}
$$

$$ (a \times d) - (b \times b) $$

#### Contoh Operasi determinan Matriks 2X2

$$ A = \begin{bmatrix}
2 & 5  \\
4 & 3  \\
\end{bmatrix}
$$

$$ (2 \times 3) - (5 \times 4) = 6 - 20 = 14 $$


## Sifat Sifat dari Determinan Matriks

In [1]:
import numpy as np

matriksA = np.array([[2,3],[1,2]])
matriksB = np.array([[1,2,3],[1,1,3],[1,4,2]])
matriksC = np.array([[1,0,],[0,1,]])
matriksD = np.array([[1,0,0],[0,1,0],[0,0,1]])


print(matriksA)
print()
print(matriksB)
print()
print(matriksC)
print()
print(matriksD)

[[2 3]
 [1 2]]

[[1 2 3]
 [1 1 3]
 [1 4 2]]

[[1 0]
 [0 1]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]


1. Sebanyak apapun ordo dari Matriks Indentitas determinannya pasti adalah 1 

In [2]:
detC = np.linalg.det(matriksC)
detD = np.linalg.det(matriksD)

print(detC)
print(detC)

1.0
1.0


2. determinan dari matriks det(AB) sama dengan det(A) x det(B).

In [3]:
matriksE = np.array([[2,1,3],[1,2,3],[1,1,2]])
matriksF = np.array([[2,1,3],[1,1,1],[3,2,3]])


detE = np.linalg.det(matriksE)
detB = np.linalg.det(matriksB)

kali1 = detE * detB
print(kali1)

0.0


3. Merubah suatu matriks akan merubah tanda dari suatu determinan pada matriks

In [4]:
matriksA = np.array([[1,4,2],[1,1,1],[3,2,1]])

matriksA1 = np.array([[1,1,1],[1,4,2],[3,2,1]])

matriksA2 = np.array([[4,1,2],[1,1,1],[2,3,1]])

detA = np.linalg.det(matriksA)
detA1 = np.linalg.det(matriksA1)
detA2 = np.linalg.det(matriksA2)


print(matriksA)
print()
print(detA.round())
print(detA1.round())
print(detA2.round())


[[1 4 2]
 [1 1 1]
 [3 2 1]]

5.0
-5.0
-5.0


4. Jika baris dari matriks merupakan kelipatan dari baris atau kolom yang lain maka akan menghasilkan nol

In [5]:
import numpy as np
matriksB = np.array([[1,4,2],[2,8,4],[3,2,1]])
matriksB1 = np.array([[1,4,2],[2,8,3],[1,4,1]])

detB = np.linalg.det(matriksB)
detB1 = np.linalg.det(matriksB1)

print(matriksB)
print(detB)
print()
print(matriksB1)
print(detB1)


[[1 4 2]
 [2 8 4]
 [3 2 1]]
0.0

[[1 4 2]
 [2 8 3]
 [1 4 1]]
0.0


5. Jika matriks A dikalikan dengan skalar, maka determinan dari Matriks A yang dikali dengan Skalar bisa di cari dengan cara, kalikan determinan A dengan skalar pangkat orde matriks

$$ det(KA) = det(A) \times k^{ordo matriks} $$

In [6]:
matriksA = np.array([[1,4,2],[1,1,1],[3,2,1]])
k = 2
matriksA1 = matriksA * 2
print(matriksA1)

print()

# Menggunakan fungsi dari python
detA1 = np.linalg.det(matriksA1)
print(detA1)

print()

#Menggunakan sifat dari determinan
detKA = 5 * 2**3
print(detKA)


[[2 8 4]
 [2 2 2]
 [6 4 2]]

40.0

40


6. Jika skalar dikalikan dengan baris 1 dari matriks pertama maka ,determinan KA bisa dicari dengan skalar dikali determinan martriks. $$ det(KA) = K \times det(A) $$


In [7]:
matriksA = np.array([[1,4,2],[1,1,1],[3,2,1]])
print(matriksA)
k = 2

print()

# Menggunakan fungsi dari py
matriksA1 = np.array([[2,8,4],[1,1,1],[3,2,1]])
detA1 = np.linalg.det(matriksA1)
print(detA1.round())

print()
# Menggunakan sifat dari determinan
detKA = 2 * 5
print(detKA)

[[1 4 2]
 [1 1 1]
 [3 2 1]]

10.0

10


7. Melakukan operasi baris elementer tidak merupah nilai determinan dari matriks tersebut

In [8]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [9]:
matriksA = np.array([[1,4,2],[1,1,1],[3,2,1]])
detA = np.linalg.det(matriksA)
print(detA.round())

print()

matriksA1 = RowAdd(matriksA,0,1,-1)
print('\n', matriksA1)

detA1 = np.linalg.det(matriksA1)
print(detA1.round())

5.0


 [[ 1.  4.  2.]
 [ 0. -3. -1.]
 [ 3.  2.  1.]]
5.0


8. Determinan matriks a tranpose sama dengan determinan matriks a.

In [10]:
matriksA = np.array([[1,4,2],[1,1,1],[3,2,1]])
detA = np.linalg.det(matriksA)

print(detA.round())

print()
transposeA = matriksA.transpose()
print(transposeA)

print()
detA1 = np.linalg.det(transposeA)
print(detA1.round())


5.0

[[1 1 3]
 [4 1 2]
 [2 1 1]]

5.0


9. determinan matriks segitiga dicari dengan mengalikan setiap elemen yang ada di matriks diagonalnya saja

In [11]:
matriksA = np.array([[1,4,2],[1,1,1],[3,2,1]])
print(matriksA)

print()

print(np.linalg.det(matriksA).round())




[[1 4 2]
 [1 1 1]
 [3 2 1]]

5.0


## Mencari Determinan Suatu Matrik ordo 4x4 menggunakan Ekspansi Kofaktor

Tentukan terlebih dahulu matriks 4x4 yang akan dicari determinannya. lalu untuk rumus yang akan digunakan adalah seperti dibawah ini. Untuk contoh soal yang saya berikan akan menggunakan baris kedua: 

$$ A_{BarisSemuaKolom} $$

Untuk contohnya adalah sebagai berikut ini

$$ A_{21}C_{21} + A_{22}C_{22} + A_{23}C_{23} + A_{24}C_{24} $$

Untuk mencari kofaktor dari setiap kolom adalah sebagai berikut ini:

$$ C_{21} = (-1)^{2+1} \times (M_{21}) $$
$$ C_{22} = (-1)^{2+2} \times (M_{22}) $$
$$ C_{23} = (-1)^{2+3} \times (M_{23}) $$
$$ C_{24} = (-1)^{2+4} \times (M_{24}) $$



In [12]:
import numpy as np
matriksF = np.array([[3,-3,4,3],[-1,0,3,-1],[-2,1,4,2],[1,-2,3,5]])
print(matriksF)


[[ 3 -3  4  3]
 [-1  0  3 -1]
 [-2  1  4  2]
 [ 1 -2  3  5]]


Mencari Determinan dari M21

$$ M_{21} = \begin{bmatrix}
-3 & 4 & 3  \\
1 & 4 & 2 \\
-2 & 3 & 5 \\
\end{bmatrix}
$$

In [13]:
print("Matriks MF21")
print()
MF21 = np.array([[-3,4,3],[1,4,2],[-2,3,5]])
print(MF21)

Matriks MF21

[[-3  4  3]
 [ 1  4  2]
 [-2  3  5]]


In [14]:

c1 =np.array([[4,3],[3,5]])
print(c1)
print()

c2 = np.array([[-3,3],[-2,5]])
print(c2)
print()

c3 = np.array([[-3,4],[-2,3]])
print(c3)
print()

m21 = 1 * ((-1)**(2+1)) *np.linalg.det(c1) + 4 * ((-1)**(2+2)) *np.linalg.det(c2) + 2 * ((-1)**(2+3)) *np.linalg.det(c3)
print(m21.round())

[[4 3]
 [3 5]]

[[-3  3]
 [-2  5]]

[[-3  4]
 [-2  3]]

-45.0


Mencari Determinan dari M22

$$ M_{22} = \begin{bmatrix}
3 & 4 & 3  \\
-2 & 4 & 2 \\
1 & 3 & 5 \\
\end{bmatrix}
$$

In [15]:
print("Matriks MF22")
print()
MF22 = np.array([[3,4,3],[-2,4,2],[1,3,5]])
print(MF22)

Matriks MF22

[[ 3  4  3]
 [-2  4  2]
 [ 1  3  5]]


In [16]:
c1 = np.array([[4,3],[4,2]])
print(c1)
print()

c2 = np.array([[3,3],[-2,2]])
print(c2)
print()

c3 = np.array([[3,4],[-2,4]])
print(c3)
print()

m22 = 1 * ((-1)**(3+1)) *np.linalg.det(c1) + 3 * ((-1)**(3+2)) *np.linalg.det(c2) + 5 * ((-1)**(3+3)) *np.linalg.det(c3)
print(m22.round())

[[4 3]
 [4 2]]

[[ 3  3]
 [-2  2]]

[[ 3  4]
 [-2  4]]

60.0


Mencari Determinan dari M23

$$ M_{23} = \begin{bmatrix}
3 & 3 & 3  \\
-2 & 1 & 2 \\
1 & -2 & 5 \\
\end{bmatrix}
$$

In [17]:
print("Matriks MF23")
print()
MF23 = np.array([[3,-3,3],[-2,1,2],[1,-2,5]])
print(MF23)

Matriks MF23

[[ 3 -3  3]
 [-2  1  2]
 [ 1 -2  5]]


In [18]:
c1 = np.array([[-3,3],[-2,5]])
print(c1)
print()

c2 = np.array([[3,3],[1,5]])
print(c2)
print()

c3 = np.array([[3,-3],[1,-2]])
print(c3)
print()

m23 = -2 * ((-1)**(2+1)) *np.linalg.det(c1) + 1 * ((-1)**(2+2)) *np.linalg.det(c2) + 2 * ((-1)**(2+3)) *np.linalg.det(c3)
print(m23.round())

[[-3  3]
 [-2  5]]

[[3 3]
 [1 5]]

[[ 3 -3]
 [ 1 -2]]

-0.0


Mencari Determinan dari M24

$$ M_{24} = \begin{bmatrix}
3 & 3 & 4  \\
-2 & 1 & 4 \\
-1 & -2 & 3 \\
\end{bmatrix}
$$

In [19]:
print("Matriks MF24")
print()
MF24 = np.array([[3,-3,4] ,[-2,1,4],[1,-2,3]])
print(MF24)

Matriks MF24

[[ 3 -3  4]
 [-2  1  4]
 [ 1 -2  3]]


In [20]:
c1 = np.array([[-3,4],[1,4]])
print(c1)
print()

c2 = np.array([[3,4],[-2,4]])
print(c2)
print()

c3 = np.array([[3,-3],[-2,1]])
print(c3)
print()

m24 = 1 * ((-1)**(3+1)) *np.linalg.det(c1) + -2 * ((-1)**(3+2)) *np.linalg.det(c2) + 3 * ((-1)**(3+3)) *np.linalg.det(c3)
print(m24.round())

[[-3  4]
 [ 1  4]]

[[ 3  4]
 [-2  4]]

[[ 3 -3]
 [-2  1]]

15.0


Setelah diketahui semua determinan dari minor matriks yang ada maka selanjutnya adalah mensubsitusi semua determinan tersebut ke dalam rumus tadi

$$ det(F) = A_{21}C_{21} + A_{22}C_{22} + A_{23}C_{23} + A_{24}C_{24} $$

cara untuk memperoleh konstanta masih sama seperti sebelumnya jadi bentuk rumusnya akan seperti ini 

$$ det(f) = A_{21} \times (-1)^{2+1} \times det(M21) + A_{22} \times (-1)^{2+2} \times det(M22) + A_{23} \times (-1)^{2+3} \times det(M23) + A_{24} \times (-1)^{2+4} \times det(M24) $$

In [21]:
detF = -1 * ((-1)**(2+1)) * m21 + 0 * ((-1)**(2+2)) * m22  + 3 * ((-1)**(2+3)) * m23 + -1 * ((-1)**(2+4)) * m24
print(detF.round())

-60.0


Jadi determinan dari suatu matriks F 4x4 diatas adalah -60