# EigenValue & EigenVector

## Penjelasan  mengenai Eigenvalue dan Eigenvector
Eigenvalue dan eigenvector adalah konsep penting dalam analisis matematika, khususnya dalam bidang linier aljabar dan statistika. Mereka digunakan secara luas dalam berbagai aplikasi, termasuk pengenalan wajah, analisis data, dan optimasi.

### Eigenvalue
Eigenvalue, juga dikenal sebagai nilai eigen, adalah nilai yang terkait dengan matriks square. Dalam konteks linear algebra, eigenvalue dari matriks A adalah niali $\lambda$ yang memenuhi persamaan berikut ini

$$ Av = \lambda v$$

dimana $\mathbf{v}$ adalah vektor non-nol yang disebut eigenvector, dan $\lambda$ adalah nilai aigenvalue. Dalam arti lain, aigenvalue adalah niali yang membuat vektor $\mathbf{v}$ menjadi vektor linear dari matriks A

### Eigenvector
Eigenvector, seperti yang disebutkan sebelumnya, adalah vektor non-nol yang memenuhii persamaan eigenvalue. Vektor ini memiliki sifat khusu bahwa ketika diterapkan pada matriks A, hasilnya adalah hasil perkalian dengan nilai eigenvalue $\lambda$. Dalam contho di atas, $\mathbf{v}$ adalah eigenvector dari matrks A dengan eigenvalue $\lambda$

### Contoh Aplikasi
Eigenvalue dan eigenvector memiliki aplikasi yang luas dalam berbagai bidang, termasuk: 

1. [Pengenalan Wajah](https://www.academia.edu/42215462/Penggunaan_PCA_Principal_Component_Analysis_): Dalam pengenalain wajah, eigenvector digunakan untuk menganalisis struktur wajah dan menemukan ciri ciri yang unik. Eigenvalue digunakan untuk menentukan skala dan orientasi dari ciri ciri tersebut

2. Analisis Data: Dalam analisis data, eigenvector digunakan untuk mengurangi dimensi data yang kompleks dan menemukan sturktur yang tersembunyi. Eigenvalue digunakan untuk menentukan signifikansi dari sturktur tersebut

## Menghitung Eigenvalue dan Eigenvector Menggunakan Library Numpy

Di zaman sekarang kita telah dimudahkan dengan teknologi yang telah tersedia, termasuk juga dengan cara kita untuk ingin mencari suatu eigenvalue dan eigenvector suatu data dengan menggunakan bahasa python dan juga library-librarynya. Saat ini saya akan mencoba mencari eigenvalue dan eigenvector dengan menggunakan bahasa python dan menggunakan libraby numpy

### Mencari Eigenvalue dan Eigenvector Matriks $2\times2$

In [1]:
import numpy as np

A = np.array([[4,1],[2,3]])

eigenvalue, eigenvector = np.linalg.eig(A)

print("Eigenvalue: ")
print(eigenvalue)
print("Eigenvector: ")
print(eigenvector.round())

Eigenvalue: 
[5. 2.]
Eigenvector: 
[[ 1. -0.]
 [ 1.  1.]]


### Mencari Eigenvalue dan Eigenvector Matriks $3\times3$

In [2]:
import numpy as np

B = np.array([[2,3,1],[2,2,4],[1,4,2]])


eigenvalue, eigenvector = np.linalg.eig(B)

print("Eigenvalue: ")
print(eigenvalue.round())
print("Eigenvector: ")
print(eigenvector.round())

Eigenvalue: 
[ 7.  1. -2.]
Eigenvector: 
[[-0. -1.  0.]
 [-1.  0. -1.]
 [-1.  0.  1.]]


## Implementasi Eigenvalue dan EigenVector


In [3]:
def pcaSVD(X):
    # Center X and get covariance matrix C
    n, p = X.shape
    X -= X.mean(axis=0)

    # SVD
    u, sigma, vt = np.linalg.svd(X, full_matrices=False)

    # Return principal compnents and eigenvalues to calculate the portion of sample variance explained
    return (X @ vt.T), (sigma**2) / (n-1)

In [4]:
import numpy as np

T = np.array([[2,1],[2,2]])


In [5]:
print(pcaSVD(T))

UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'