In [1]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

# *Materi Invers Matriks*

## Penjelasan dari Matriks Invers
Invers Matriks adalah adalah sebuah matriks baru yang merupakan kebalikan dari matriks asal dengan notasi A-1. Jika Matriks tersebut dikalikan dengan inversnya, hasilnya adalah matriks identitas. Invers Matriks dapat diperoleh dari berbagai macam metode seperti menggunakan eliminasi gaussi seperti materi yang kita pelajari sebelumnya. Matriks invers adalah penting ketika mengerjakan soal-soal dalam sebuah matriks, sebab ia dapat memecahkan sistem persamaan linier. 

## sifat sifat matriks invers

Invers matriks mempunyai sifat sifat bisa dikenali dan membedakannya dari matriks biasa adalah : 


1. $$ (A^{-1})^{-1} $$
2. $$ A^{-1} . A = A . A^{-1} = I $$
3. $$ AB = I  (artinya \; A \; dan \; B \; saling \; invers,\; yaitu A^{-1} = B \; dan \; B^{-1} = A ) $$
4. $$ (AB)^{-1} = B^{-1} . A^{-1} $$
5. $$ AB = C \; maka \; A = C.B^{-1} \;,\; B = A^{-1} . C $$


[sifat](https://www.konsep-matematika.com/2015/09/sifat-sifat-determinan-dan-invers.html) 

## Mencari Invers Matriks dengan menggunakan metode eliminasi Gaus Jordan

berikut ini adalah contoh matriks beserta dengan bagaimana cara mencari invers matriks menggunakan eliminasi gauss jordan serta pembuktian dari perhitungan secara langsung menggunakan library numpy python agar lebih pasti.

In [2]:
import numpy as np

# Contoh dari matriks yang ditambahkan dengan matriks identitas di sebelahnya agar bisa di cari invers matriksnya
a = np.array([[1,2,1, 1,0,0],[4,1,4, 0,1,0],[4,4,2, 0,0,1]])
print(a)

[[1 2 1 1 0 0]
 [4 1 4 0 1 0]
 [4 4 2 0 0 1]]


In [3]:
# Ini adalah perhitungan secara manual menggunakan eliminasi gauss jordan dan ditemukan hasil akhirnya seperti yang dibawah tersebut
a1 = RowAdd(a,1,2,-1)
print(a1,'\n')

a2 = RowAdd(a1,0,1,-4)
print(a2,'\n')

a3 = RowScale(a2,1,-1/7)
print(a3,'\n')

a4 = RowAdd(a3,1,2,-3)
print(a4,'\n')

a5 = RowScale(a4,2,-1/2)
print(a5,'\n')

a6 = RowAdd(a5,2,0,-1)
print(a6,'\n')

a7 = RowAdd(a6,1,0,-2)
print(a7,'\n')


[[ 1.  2.  1.  1.  0.  0.]
 [ 4.  1.  4.  0.  1.  0.]
 [ 0.  3. -2.  0. -1.  1.]] 

[[ 1.  2.  1.  1.  0.  0.]
 [ 0. -7.  0. -4.  1.  0.]
 [ 0.  3. -2.  0. -1.  1.]] 

[[ 1.          2.          1.          1.          0.          0.        ]
 [-0.          1.         -0.          0.57142857 -0.14285714 -0.        ]
 [ 0.          3.         -2.          0.         -1.          1.        ]] 

[[ 1.          2.          1.          1.          0.          0.        ]
 [-0.          1.         -0.          0.57142857 -0.14285714 -0.        ]
 [ 0.          0.         -2.         -1.71428571 -0.57142857  1.        ]] 

[[ 1.          2.          1.          1.          0.          0.        ]
 [-0.          1.         -0.          0.57142857 -0.14285714 -0.        ]
 [-0.         -0.          1.          0.85714286  0.28571429 -0.5       ]] 

[[ 1.          2.          0.          0.14285714 -0.28571429  0.5       ]
 [-0.          1.         -0.          0.57142857 -0.14285714 -0.        

In [4]:
# Ini adalah matriks yang tanpa menggunakan matriks identitas 
a = np.array([[-1,0,0.5],[0.57142857,-0.14285714,0],[0.85714286,0.28571429,-0.5]])
print(a)

print()

# Method numpy yang dapat digunakan untuk pembuktian invers matriks
a_inv = np.linalg.inv(a)
print(a_inv)

[[-1.          0.          0.5       ]
 [ 0.57142857 -0.14285714  0.        ]
 [ 0.85714286  0.28571429 -0.5       ]]

[[0.99999996 1.99999999 0.99999996]
 [3.99999991 0.99999996 3.99999991]
 [3.99999992 3.99999998 1.99999992]]


## Tugas soal 4 persamaan 4 variabel cari solusinya pakai invers matriks

### *Contoh Soal Tugas 4 Persamaan 4 Variabel*

$$ x_1 - x_2 + 2x_3 - 1x_4 = 4 $$
$$ 2x_1 - 2x_2 + 3x_3 - 2x_4 = -2 $$
$$ x_1 + x_2 + 1x_3 = 3 $$
$$ x_1 - 1x_2 - 4x_3 + 3x_4 = 6 $$


Konversikan persamaan linier 4 variabel ini menjadi matriks agar dapat dicari berapa invers matriksnya melalui metode eliminasi gaus jordan. kita pisahkan menjadi 2 matriks yaitu matriks A untuk menampung persamaan linier, sedangkan matriks B yang menampung sama dengan dari persamaan linier

$$
\begin{bmatrix}
1 & -1 & 2 & -1 \\
2 & -2 & 3 & -3 \\
1 & 1 & 1 & 0 \\
1 & -1 & 4 & 3 \\
\end{bmatrix}
$$

$$
\begin{bmatrix}
4 \\
-2 \\
3 \\
6 \\
\end{bmatrix}
$$

jangan lupa menggunakan matriks identitas untuk merubah matriks di atas. berikut ini adalah bentuk matriks identitas yang kita akan pakai.

$$
\begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \\
\end{bmatrix}
$$

selanjutnya adalah mengooperasikan metode sistem eliminasi gaus jordan



In [5]:
# Bentuk matriks yang sudah dipasangkan dengan matriks identitas dan akan dibuah menjadi matriks invers
import numpy as np

b = np.array([[1,-1,2,-1, 1,0,0,0], [2,-2,3,-3, 0,1,0,0], [1,1,1,0, 0,0,1,0], [1,-1,4,3, 0,0,0,1]])
print(b)


[[ 1 -1  2 -1  1  0  0  0]
 [ 2 -2  3 -3  0  1  0  0]
 [ 1  1  1  0  0  0  1  0]
 [ 1 -1  4  3  0  0  0  1]]


In [6]:
b1 = RowAdd(b,0,1,-2)
print(b1,'\n')

[[ 1. -1.  2. -1.  1.  0.  0.  0.]
 [ 0.  0. -1. -1. -2.  1.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  1.  0.]
 [ 1. -1.  4.  3.  0.  0.  0.  1.]] 



In [7]:
b2 = RowAdd(b1,0,2,-1)
print(b2,'\n')

[[ 1. -1.  2. -1.  1.  0.  0.  0.]
 [ 0.  0. -1. -1. -2.  1.  0.  0.]
 [ 0.  2. -1.  1. -1.  0.  1.  0.]
 [ 1. -1.  4.  3.  0.  0.  0.  1.]] 



In [8]:
b3 = RowAdd(b2,0,3,-1)
print(b3,'\n')

[[ 1. -1.  2. -1.  1.  0.  0.  0.]
 [ 0.  0. -1. -1. -2.  1.  0.  0.]
 [ 0.  2. -1.  1. -1.  0.  1.  0.]
 [ 0.  0.  2.  4. -1.  0.  0.  1.]] 



In [9]:
b4 = RowSwap(b3,1,2,)
print(b4,'\n')

[[ 1. -1.  2. -1.  1.  0.  0.  0.]
 [ 0.  2. -1.  1. -1.  0.  1.  0.]
 [ 0.  0. -1. -1. -2.  1.  0.  0.]
 [ 0.  0.  2.  4. -1.  0.  0.  1.]] 



In [10]:
b5 = RowScale(b4,1,1/2)
print(b5,'\n')

[[ 1.  -1.   2.  -1.   1.   0.   0.   0. ]
 [ 0.   1.  -0.5  0.5 -0.5  0.   0.5  0. ]
 [ 0.   0.  -1.  -1.  -2.   1.   0.   0. ]
 [ 0.   0.   2.   4.  -1.   0.   0.   1. ]] 



In [11]:
b6 = RowScale(b5,3,1/2)
print(b6,'\n')

[[ 1.  -1.   2.  -1.   1.   0.   0.   0. ]
 [ 0.   1.  -0.5  0.5 -0.5  0.   0.5  0. ]
 [ 0.   0.  -1.  -1.  -2.   1.   0.   0. ]
 [ 0.   0.   1.   2.  -0.5  0.   0.   0.5]] 



In [12]:
b7 = RowAdd(b6,2,3,1)
print(b7,'\n')

[[ 1.  -1.   2.  -1.   1.   0.   0.   0. ]
 [ 0.   1.  -0.5  0.5 -0.5  0.   0.5  0. ]
 [ 0.   0.  -1.  -1.  -2.   1.   0.   0. ]
 [ 0.   0.   0.   1.  -2.5  1.   0.   0.5]] 



In [13]:
b8 = RowAdd(b7,1,0,1)
print(b8,'\n')

[[ 1.   0.   1.5 -0.5  0.5  0.   0.5  0. ]
 [ 0.   1.  -0.5  0.5 -0.5  0.   0.5  0. ]
 [ 0.   0.  -1.  -1.  -2.   1.   0.   0. ]
 [ 0.   0.   0.   1.  -2.5  1.   0.   0.5]] 



In [14]:
b9 = RowAdd(b8,3,2,1)
print(b9,'\n')

[[ 1.   0.   1.5 -0.5  0.5  0.   0.5  0. ]
 [ 0.   1.  -0.5  0.5 -0.5  0.   0.5  0. ]
 [ 0.   0.  -1.   0.  -4.5  2.   0.   0.5]
 [ 0.   0.   0.   1.  -2.5  1.   0.   0.5]] 



In [15]:
b10 = RowAdd(b9,2,0,1.5)
print(b10,'\n')

[[ 1.    0.    0.   -0.5  -6.25  3.    0.5   0.75]
 [ 0.    1.   -0.5   0.5  -0.5   0.    0.5   0.  ]
 [ 0.    0.   -1.    0.   -4.5   2.    0.    0.5 ]
 [ 0.    0.    0.    1.   -2.5   1.    0.    0.5 ]] 



In [16]:
b11 = RowAdd(b10,2,1,-0.5)
print(b11,'\n')

[[ 1.    0.    0.   -0.5  -6.25  3.    0.5   0.75]
 [ 0.    1.    0.    0.5   1.75 -1.    0.5  -0.25]
 [ 0.    0.   -1.    0.   -4.5   2.    0.    0.5 ]
 [ 0.    0.    0.    1.   -2.5   1.    0.    0.5 ]] 



In [17]:
b12 = RowScale(b11,2,-1)
print(b12,'\n')

[[ 1.    0.    0.   -0.5  -6.25  3.    0.5   0.75]
 [ 0.    1.    0.    0.5   1.75 -1.    0.5  -0.25]
 [-0.   -0.    1.   -0.    4.5  -2.   -0.   -0.5 ]
 [ 0.    0.    0.    1.   -2.5   1.    0.    0.5 ]] 



In [18]:
b13 = RowAdd(b12,3,1,-0.5)
print(b13,'\n')

[[ 1.    0.    0.   -0.5  -6.25  3.    0.5   0.75]
 [ 0.    1.    0.    0.    3.   -1.5   0.5  -0.5 ]
 [-0.   -0.    1.   -0.    4.5  -2.   -0.   -0.5 ]
 [ 0.    0.    0.    1.   -2.5   1.    0.    0.5 ]] 



In [19]:
b14 = RowAdd(b13,3,0,0.5)
print(b14,'\n')

[[ 1.   0.   0.   0.  -7.5  3.5  0.5  1. ]
 [ 0.   1.   0.   0.   3.  -1.5  0.5 -0.5]
 [-0.  -0.   1.  -0.   4.5 -2.  -0.  -0.5]
 [ 0.   0.   0.   1.  -2.5  1.   0.   0.5]] 



jika kita sudah menemukan invers matriksnya maka langkah selanjutnya adalah kita mengalikan matriks yang sudah kita invers tadi dengan matriks B yaitu hasil sama dengan persamaan linier tadi. 

$X = A^{-1}B = \begin{bmatrix} -7.5 & 3.5 & 0.5 & 1 \\ 3 & -1.5 & 0.5 & -0.5 \\ 4.5 & -2 & 0 & -0.5 \\ -2.5 & 1 & 0 & 0.5 \end{bmatrix}$ x $\begin{bmatrix} 4 \\ -2 \\ 3 \\ 6 \end{bmatrix}$

In [20]:
import numpy as np

b_invers = np.array([[-7.5,3.5,0.5,1],[3,-1.5,0.5,-0.5],[4.5,-2,0,0.5],[-2.5,1,0,0.5]])
b = np.array([[4],[-2],[3],[6]])

x = b_invers @ b

print(x)


[[-29.5]
 [ 13.5]
 [ 25. ]
 [ -9. ]]


x1 = 2
x2 = 1
x3 = 0

x1 + x2 + x3 = 3
2x1 + x2 + 3x3 = 5
x1 - 2x2 + x3 = 0

In [21]:
t100 = np.array([[1,1,1], [2,1,3],[1,-2,1]])
invers = np.linalg.inv(t100)
print(invers)
print()
c = invers @ t100
print(f'c \n{c}')

bulat = np.round(invers)
print(bulat)

[[ 2.33333333e+00 -1.00000000e+00  6.66666667e-01]
 [ 3.33333333e-01  2.22044605e-17 -3.33333333e-01]
 [-1.66666667e+00  1.00000000e+00 -3.33333333e-01]]

c 
[[ 1.00000000e+00  2.22044605e-16  8.88178420e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  0.00000000e+00  1.00000000e+00]]
[[ 2. -1.  1.]
 [ 0.  0. -0.]
 [-2.  1. -0.]]


In [22]:
o = np.array([[1,1,1, 1,0,0,], [2,1,3, 0,1,0,], [1,-2,1, 0,0,1]])
print(o)


[[ 1  1  1  1  0  0]
 [ 2  1  3  0  1  0]
 [ 1 -2  1  0  0  1]]


In [23]:
o1 = RowAdd(o,0,1,-2)
print(o1,'\n')

[[ 1.  1.  1.  1.  0.  0.]
 [ 0. -1.  1. -2.  1.  0.]
 [ 1. -2.  1.  0.  0.  1.]]

In [24]:
o2 = RowAdd(o1,0,2,-1)
print(o2,'\n')

[[ 1.  1.  1.  1.  0.  0.]
 [ 0. -1.  1. -2.  1.  0.]
 [ 0. -3.  0. -1.  0.  1.]]

In [25]:
o3 = RowScale(o2,1,1/-1)
print(o3,'\n')

[[ 1.  1.  1.  1.  0.  0.]
 [-0.  1. -1.  2. -1. -0.]
 [ 0. -3.  0. -1.  0.  1.]] 



In [26]:
o4 = RowAdd(o3,1,0,-1)
print(o4,'\n')

[[ 1.  0.  2. -1.  1.  0.]
 [-0.  1. -1.  2. -1. -0.]
 [ 0. -3.  0. -1.  0.  1.]] 



In [27]:
o5 = RowAdd(o4,1,2,3)
print(o5,'\n')

[[ 1.  0.  2. -1.  1.  0.]
 [-0.  1. -1.  2. -1. -0.]
 [ 0.  0. -3.  5. -3.  1.]] 



In [28]:
o6 = RowScale(o5,2,1/-3)
print(o6,'\n')

[[ 1.          0.          2.         -1.          1.          0.        ]
 [-0.          1.         -1.          2.         -1.         -0.        ]
 [-0.         -0.          1.         -1.66666667  1.         -0.33333333]] 



In [29]:
o7 = RowAdd(o6,2,1,1)
print(o7,'\n')

[[ 1.          0.          2.         -1.          1.          0.        ]
 [-0.          1.          0.          0.33333333  0.         -0.33333333]
 [-0.         -0.          1.         -1.66666667  1.         -0.33333333]] 



In [30]:
o8 = RowAdd(o7,2,0,-2)
print(o8,'\n')

[[ 1.          0.          0.          2.33333333 -1.          0.66666667]
 [-0.          1.          0.          0.33333333  0.         -0.33333333]
 [-0.         -0.          1.         -1.66666667  1.         -0.33333333]] 



In [31]:
import numpy as np

tugas_invers = np.array([[2.33333333,-1,0.66666667],[0.33333333,0,-0.33333333],[-1.66666667,1,-0.33333333]])
tugas = np.array([[3],[5],[0]])

j = tugas_invers @ tugas
j1 = np.round(j)

print(j)
print()
print(j1)


[[ 1.99999999e+00]
 [ 9.99999990e-01]
 [-9.99999972e-09]]

[[ 2.]
 [ 1.]
 [-0.]]
